### ISSUE TITLE
how do I install it?

### ISSUE THREAD

**Issue by kdamianakis** [eflynch/magnolial#1]
Hi,

Just wonder what is the best way to install?

Regards,
K.

**Comment by eflynch** [comment]
You can either run it in the browser (in which case you need to serve the app directory) or you can run it with Electron as .app bundle. The .app bundle for the newest version is in the releases. No "installation" should be necessary, but if it's throwing errors about files/folders being missing you can try creating ~/.magnolial/.

Also feel free to working on it if it's interesting to you, I'm doing a ton with it at the moment. The next feature I wanted to implement was a better interface for setting keybindings. (at the moment there are basically two sets of keybindings you can go between. One is VIM-inspired, the other is more generic)

**Comment by kdamianakis** [comment]
Hi,

Thank you for this! I shall give it a try..

Is there a way that it can be served via nginx or apache? Is that what the ‘run in the browser’ can be or is it only as a localised application? Will need to do some reading :)

Kind Regards,
Konstantinos Damianakis

**Comment by eflynch** [comment]
It's maybe a bit of an unusual architecture because I conceived of it as a client app that can run separately from any server but can potentially interface with any server that has the write spec. That's probably not great from a security stand-point but I was mostly imagining running it locally anyway. That said, there is no reason you can't run a public-facing server for the app to talk to. 


In more detail:
It's an all-client-side app so you can serve it from the file system, via apache, nginx, locally or not, doesn't matter as long as you browser downloads the files.

However, if you want to open and save files you obviously need a server of some kind when you are running it in the browser. https://github.com/eflynch/magnolial-server is a basic server designed to work for that. Check out magnolial-io.js, node-io.js, and browser-io.js to get a sense of how I conceived of reading/writing files. Basically you "open" and "save" to a URL if the server hosting it is set up to take POST, PATCH, and GET correctly (magnolial-server). And if you are running in Electron/Node you can do that or open/save to a local file in the file system with a UNIX path.

So, if you run magnolial-server on localhost:5000, you can open the client app in the browser and "open" "http://localhost:5000/m/newfile.mgl."

**Comment by eflynch** [comment]
I'm going to close this. Feel free to re-open for any reason
