### ISSUE TITLE
Electron package syntax no longer valid?

### ISSUE THREAD

**Issue by inakarmacoma** [eflynch/magnolial#2]
Absolutely love the idea of a WorkFlowy clone. Spent all day trying to install, but both direct drag to Electron, as well as git clone, npm install, and npm start fail on Windows 10. Looks like one of the Window methods was deprecated. Any thoughts on how I might be able to get this running? It sounds awesome. 

177 verbose stack Error: magnolial@0.0.1 install: `cp -r ./build/Magnolial.app /Applications/Magnolial.app`
177 verbose stack Exit status 1
177 verbose stack     at EventEmitter.<anonymous> (E:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
177 verbose stack     at emitTwo (events.js:106:13)
177 verbose stack     at EventEmitter.emit (events.js:191:7)
177 verbose stack     at ChildProcess.<anonymous> (E:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
177 verbose stack     at emitTwo (events.js:106:13)
177 verbose stack     at ChildProcess.emit (events.js:191:7)
177 verbose stack     at maybeClose (internal/child_process.js:920:16)
177 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
178 verbose pkgid magnolial@0.0.1
179 verbose cwd C:\Users\*\electron-quick-start\magnolial
180 error Windows_NT 10.0.15063
181 error argv "E:\\Program Files\\nodejs\\node.exe" "E:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
182 error node v6.11.4
183 error npm  v3.10.10
184 error code ELIFECYCLE
185 error magnolial@0.0.1 install: `cp -r ./build/Magnolial.app /Applications/Magnolial.app`
185 error Exit status 1
186 error Failed at the magnolial@0.0.1 install script 'cp -r ./build/Magnolial.app /Applications/Magnolial.app'.
186 error Make sure you have the latest version of node.js and npm installed.
186 error If you do, this is most likely a problem with the magnolial package,
186 error not with npm itself.
186 error Tell the author that this fails on your system:
186 error     cp -r ./build/Magnolial.app /Applications/Magnolial.app
186 error You can get information on how to open an issue for this project with:
186 error     npm bugs magnolial
186 error Or if that isn't available, you can get their info via:
186 error     npm owner ls magnolial
186 error There is likely additional logging output above.
187 verbose exit [ 1, true ]

**Comment by eflynch** [comment]
Hmmm.. TBH I've never tried it in Windows and I haven't been keeping up with changes to Electron. The npm run scripts `build` and `install` are not going to work out of the box because I didn't version the build directory which contains the empty electron `Magnolial.app` bundle. Since you are building on windows I imagine you will need to do something different in any case since the `.app` bundle is a Mac thing. If you want to run it in Electron I would start with the Electron guide knowing that magnolial still definitely works as a static web application.

An alternative is to just run it as a web-app by serving the app directory locally with something like
`python3 -m http.server 8080`.

The files that actually interact with the Electron framework and file system are`src/node-io.js` and `app/main.js`. I imagine any deprecated Electron API stuff is there. I don't have time to maintain this package, but would be happy to help you get it working if I can, and would review pull requests.

Also a word of warning, the keybindings I have by default are pretty idiosyncratic as is the file saving interface...

Cheers!

**Comment by eflynch** [comment]
I'm going to close this. Feel free to re-open for any reason.
